{{- if and .Values.mongodb.enabled (not .Values.mongodb.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.secretName }}
  labels:
    {{- include "eagle-demi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.mongodb.usernameKey }}: {{ .Values.mongodb.credentials.username | default "demi" | quote }}
  {{ .Values.mongodb.passwordKey }}: {{ .Values.mongodb.credentials.password | default "demi_pass_123" | quote }}
  {{ .Values.mongodb.databaseKey }}: {{ .Values.mongodb.credentials.database | default "demi" | quote }}
  {{ .Values.mongodb.adminPasswordKey }}: {{ .Values.mongodb.credentials.adminPassword | default "admin_pass_123" | quote }}
{{- end }}

